/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as LesClassesRouteImport } from './routes/les-classes'
import { Route as NotreEcoleRouteImport } from './routes/notre-ecole'
import { Route as ProjetEducatifRouteImport } from './routes/projet-educatif'
import { Route as VieScolaireRouteImport } from './routes/vie-scolaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const LesClassesRoute = LesClassesRouteImport.update({
  id: '/les-classes',
  path: '/les-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreEcoleRoute = NotreEcoleRouteImport.update({
  id: '/notre-ecole',
  path: '/notre-ecole',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetEducatifRoute = ProjetEducatifRouteImport.update({
  id: '/projet-educatif',
  path: '/projet-educatif',
  getParentRoute: () => rootRouteImport,
} as any)
const VieScolaireRoute = VieScolaireRouteImport.update({
  id: '/vie-scolaire',
  path: '/vie-scolaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/les-classes': typeof LesClassesRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/projet-educatif': typeof ProjetEducatifRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/les-classes': typeof LesClassesRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/projet-educatif': typeof ProjetEducatifRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/les-classes': typeof LesClassesRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/projet-educatif': typeof ProjetEducatifRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galerie'
    | '/les-classes'
    | '/notre-ecole'
    | '/projet-educatif'
    | '/vie-scolaire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galerie'
    | '/les-classes'
    | '/notre-ecole'
    | '/projet-educatif'
    | '/vie-scolaire'
  id:
    | '__root__'
    | '/'
    | '/galerie'
    | '/les-classes'
    | '/notre-ecole'
    | '/projet-educatif'
    | '/vie-scolaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalerieRoute: typeof GalerieRoute
  LesClassesRoute: typeof LesClassesRoute
  NotreEcoleRoute: typeof NotreEcoleRoute
  ProjetEducatifRoute: typeof ProjetEducatifRoute
  VieScolaireRoute: typeof VieScolaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/les-classes': {
      id: '/les-classes'
      path: '/les-classes'
      fullPath: '/les-classes'
      preLoaderRoute: typeof LesClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-ecole': {
      id: '/notre-ecole'
      path: '/notre-ecole'
      fullPath: '/notre-ecole'
      preLoaderRoute: typeof NotreEcoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projet-educatif': {
      id: '/projet-educatif'
      path: '/projet-educatif'
      fullPath: '/projet-educatif'
      preLoaderRoute: typeof ProjetEducatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vie-scolaire': {
      id: '/vie-scolaire'
      path: '/vie-scolaire'
      fullPath: '/vie-scolaire'
      preLoaderRoute: typeof VieScolaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalerieRoute: GalerieRoute,
  LesClassesRoute: LesClassesRoute,
  NotreEcoleRoute: NotreEcoleRoute,
  ProjetEducatifRoute: ProjetEducatifRoute,
  VieScolaireRoute: VieScolaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
